### PR TITLE
Fix Flight Paths directions query

### PR DESCRIPTION
**Pull request by d-asmaa**
- [x] Fixed the flight paths query

### CODE REVIEW

**Comment by osfameron** [comment]
This looks good! @maria-robobug we should check if the logic was inverted previously to our refactor, and whether that applies to any other sample app

**Comment by maria-robobug** [comment]
Hmm, seems `mobile-travel-sample-tutorial` branch is 11 commits ahead, 12 commits behind `7.0`.
Is this branch based off an older version of the app?

From what I can see from 6.5 branch onwards this seems to be correct: https://github.com/couchbaselabs/try-cb-python/blob/6.5/travel.py#L132-L133

Maybe 5.0/6.0 branch caused the confusion?
https://github.com/couchbaselabs/try-cb-python/blob/5.0/travel.py#L129-L130
https://github.com/couchbaselabs/try-cb-python/blob/6.0/travel.py#L129-L130

But ultimately, do we need to update the `mobile-travel-sample-tutorial` to be in sync with 7.0 updates?

**Comment by d-asmaa** [comment]
@maria-robobug The mobile-travel-sample tutorial is used for the Travel Demo with CB server 6.5
https://docs.couchbase.com/tutorials/mobile-travel-sample/java/installation/manual.html

**Comment by osfameron** [comment]
Oh! My bad, I hadn't checked the target branch...
Yeah, sorry, probably not relevant to our Docs sample (the 7.0) branch, but it would be really good to know what's happening in the other branches :) is this related to what we discussed with @biozal ?

**Comment by d-asmaa** [comment]
@osfameron Is it possible to review the changes before the end of the week please. It will be used for the mobile workshop on next tuesday ( 17/08)

**Review by maria-robobug — APPROVED** [review]
👍 LGTM

**Comment by osfameron** [comment]
@d-asmaa the inverted date commit is fine.

The javascript one is the wrong approach: you'd ideally want to update the *source* code in the try-cb-frontend project and then build the minified code. It's really hard to review in this format (and must have been really hard for you to debug and edit!)

As discussed, if you go on to update to our 7.0 backend, this is all a bit easier to manage (no minified JS source to wrestle with!)

I'm sure this is fine however 👍  (and doesn't affect us, as we're using the 7.0 branch).

**Pull request merged**
