### PR TITLE
Connect the application to capella

### PR DESCRIPTION
**Pull request by d-asmaa**
The branch should not be merged till we update the dockerfile

### CODE REVIEW

**Comment by osfameron** [comment]
Thanks Asmaa! I now plan to:

* update the Dockerfile (with overrides in compose file)
* simplify the configuration passing (and parsing)
* test workflow for both local AND capella server
* update README.md with appropriate documentation on setting up the Capella and index
* Squash the commits before final review and merge

**Comment by osfameron** [comment]
This is now ready for review!

**Comment by osfameron** [comment]
@krugster asked for status update on this - I think this was good to go and just required review.

@maria-robobug @thejcfactor could you give a quick once-over?

**Comment by maria-robobug** [comment]
Looking at sample apps on Friday, will add this to the list of things to go over! 👍

**Pull request merged**
